# Generated by Django 5.0.2 on 2024-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_admin_authenticated_user_is_subuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent_user_group_name',
            field=models.TextField(default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.TextField(default='Null', null=True),
        ),
    ]
