# Generated by Django 5.0.2 on 2024-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_parent_user_group_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('time', models.DateTimeField()),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Verification_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
