# Generated by Django 5.0.2 on 2024-03-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_email_timer_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_timer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='verification_code',
            name='id',
        ),
        migrations.AlterField(
            model_name='email_timer',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='verification_code',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
