# Generated by Django 5.0.2 on 2024-03-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_email_timer_id_remove_verification_code_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_timer',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
