# Generated by Django 5.0.2 on 2024-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_group',
            field=models.TextField(default='Null', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='user_group',
            field=models.TextField(default='Null', null=True),
        ),
    ]
